// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class DodajwyjazdTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void dodaj() {
    driver.get("https://localhost:5001/");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    driver.findElement(By.linkText("Zaloguj się")).click();
    driver.findElement(By.id("Input_Email")).click();
    driver.findElement(By.id("Input_Email")).sendKeys("superadmin");
    driver.findElement(By.cssSelector(".col-md-4")).click();
    driver.findElement(By.cssSelector(".form-group:nth-child(4)")).click();
    driver.findElement(By.id("Input_Password")).click();
    driver.findElement(By.id("Input_Password")).sendKeys("!Admin321");
    driver.findElement(By.cssSelector(".btn")).click();
    driver.findElement(By.linkText("Wyjazdy")).click();
    driver.findElement(By.linkText("Dodaj nowy")).click();
    driver.findElement(By.id("Data")).click();
    driver.findElement(By.id("Data")).sendKeys("2022-03-10T14:54");
    driver.findElement(By.id("Miejsce")).click();
    driver.findElement(By.id("Miejsce")).sendKeys("Kraków, ul. Wiejska 7");
    driver.findElement(By.id("Rodzaj_zdarzeniaId")).click();
    {
      WebElement dropdown = driver.findElement(By.id("Rodzaj_zdarzeniaId"));
      dropdown.findElement(By.xpath("//option[. = 'Miejscowe zagrożenie']")).click();
    }
    driver.findElement(By.id("Strazacy")).click();
    driver.findElement(By.id("Strazacy")).sendKeys("Jan Kowalski, Janek Kowalski, Janusz Kowalski, Jarosław Kowalski");
    driver.findElement(By.id("SamochodyId")).click();
    driver.findElement(By.id("SamochodyId2")).click();
    {
      WebElement dropdown = driver.findElement(By.id("SamochodyId2"));
      dropdown.findElement(By.xpath("//option[. = 'GCBA 5/2.5']")).click();
    }
    driver.findElement(By.id("Opis")).click();
    driver.findElement(By.id("Opis")).sendKeys("Wypadek drogowy");
    driver.findElement(By.cssSelector(".btn-primary")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(2)")).getText(), is("Kraków, ul. Wiejska 7"));
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(1) > td:nth-child(3)")).getText(), is("Miejscowe zagrożenie"));
  }
}
